# ____       _      _   _   _  __  ____
#|  _ \     / \    | \ | | | |/ / / ___|
#| |_) |   / _ \   |  \| | | ' /  \___ \
#|  _ <   / ___ \  | |\  | | . \   ___) |
#|_| \_\ /_/   \_\ |_| \_| |_|\_\ |____/

name: RanksPlugin
version: 1.0.0
main: julien\ranksplugin\Main
api: ['4.0.0']
author: Julien